### ISSUE TITLE
Critical mistakes in files

### ISSUE THREAD

**Issue by timiks** [pichillilorenzo/JavaScript-Completions#1]
I've installed this package for Sublime Text 2 now and noticed that main completions aren't working. I noticed that only “description” completions are working. After some investigations, disabling Emmet and even SublimeCodeIntel (I thought they can affect work of this package) the problem was still.

And you know what's the trick? In your source files (.sublime-completions) you left comma “,” after every last JSON-object :) Result — bad syntax in your important files, everything is not working. I didn't look at every file, but definitely some of  them with bad syntax. Quickly fix it!

**Comment by bakman2** [comment]
Still not working for me, same behaviour as timyusupov. 
Some things work but like ```document``` doesnt.
