### ISSUE TITLE
Sublime Text 2: Trailing comma before closing bracket in range.sublime, number.sublime, treewalker.sublime

### ISSUE THREAD

**Issue by bhawdeadlydan** [pichillilorenzo/JavaScript-Completions#10]
Sublime Text 2
Error trying to parse settings: Trailing comma before closing bracket in ~/Library/Application Support/Sublime Text 2/Packages/JavaScript Completions/sublime-completions/range.sublime-settings:30:3

Even the default settings have extra comma in the end which is making it fail.
"description-jquery": false,  <--

**Comment by pichillilorenzo** [comment]
Thank you! I updated it!
