### ISSUE TITLE
Extra space in the function body

### ISSUE THREAD

**Issue by Henerator** [pichillilorenzo/JavaScript-Completions#11]
When I use autocompletion for function declarations, it adds an extra space before the comment in the function body. Didn't want to bother you with such a trivial matter, but have not figured out how to fix it.

**Comment by pichillilorenzo** [comment]
I updated it! Check now!

**Comment by Henerator** [comment]
It's weird. Reinstalled the plugin, but gaps remained. Added your fix by hand. Thank you for your plugin.

**Comment by pichillilorenzo** [comment]
Thank you for the support! However I'm going to release a new update with another "feature" soon and I will release also an update about a better descriptions of functions etc.
