### ISSUE TITLE
Autocomplete list at the end of the line

### ISSUE THREAD

**Issue by mishkeTz** [pichillilorenzo/JavaScript-Completions#12]
Hi,
I have some annoying issue with my ST3 JavaScript Completions package. So, whenever I hit space even If I haven't write anything yet I get JS autocomplete list with bunch of different functions and every time when I want to go to the next line I can't because there is that autocomplete list and I need to click esc button first to remove that list and than click enter so I can move on to the next line. It is pretty annoying when code is a bit longer, every time at the end of the line I need to click esc and than enter.

I don't want to remove that plugin, it's quite useful but I haven't this problem until today. I tried to reinstall that package but I still have the same problem.

Here is an example how it looks. My cursor is at the end of the line, after semicolon.
![js-st](https://cloud.githubusercontent.com/assets/15350199/18613714/5ed3be1a-7d80-11e6-9933-ca674aa22775.png)

**Comment by pichillilorenzo** [comment]
I tried but i can't reproduce this bug! Which exact version of Sublime Text are you using?? Mine is Build 3114

**Comment by pichillilorenzo** [comment]
Try uninstall it and after download this folder: https://www.dropbox.com/sh/mcs6ny1786yw54l/AADV4TgV9UV7ZuW9SZHG595ha?dl=0

It contains the plugin but i added a check for my completions. Copy the folder into the "Packages" folder of Sublime Text 3. 

Let me know if there are problems. If not, i will update officially the plugin.

**Comment by mishkeTz** [comment]
Thanks, It solved the problem. Everything works fine now.

**Comment by pichillilorenzo** [comment]
Thank you for the support! So i'm going to update this plugin officially!
