### ISSUE TITLE
Awesome 'Can I use'

### ISSUE THREAD

**Issue by infobeny** [pichillilorenzo/JavaScript-Completions#15]
Hello @pichillilorenzo, just didn't find out any other way how to directly (here, public) say 'Awesome, thank you!' :+1: That new function 'Can I use' is really amazing and so usefull. Keep doing so good stuff with your plugin. Thank You!

**Comment by pichillilorenzo** [comment]
Really thank you @infobeny for the support! 

Like I said on the project description, I use data that comes from this [repository](https://github.com/Fyrd/caniuse)!
I thank @Fyrd for this data! Without it I could never do this feature! :simple_smile:

**Comment by Yhubee** [comment]
Just opened sublime and saw the feature. It truly is awesome @pichillilorenzo 

+ 1000 👍
