### ISSUE TITLE
Can't use Context menu options

### ISSUE THREAD

**Issue by zDragon117** [pichillilorenzo/JavaScript-Completions#20]
Is it a bug or something?
Although i have selected the text, Surround With options still don't show up. So the Sort array option is.

![image](https://cloud.githubusercontent.com/assets/23108004/19784941/c7d1de00-9cc1-11e6-9bbf-0a95d008be53.png)

When i restart sublime text, like the first 1 second i right click and see context menu. But after that, it seem hide and i can't see it anymore like above.

![image](https://cloud.githubusercontent.com/assets/23108004/19785146/8b7f81a4-9cc2-11e6-8043-d7e8ac9c93a8.png)

**Comment by pichillilorenzo** [comment]
The problem is that the scope of the view is HTML and not JS.. Infact the syntax is setted to HTML.. I will fix this problem soon as possible! 

Thanks to the support.

**Comment by victorwpbastos** [comment]
The same problem happens with `vue` files too.

**Comment by pichillilorenzo** [comment]
Try the new version and let me know!!
Thanks to the support!
