### ISSUE TITLE
menu not going away

### ISSUE THREAD

**Issue by cameronroe** [pichillilorenzo/JavaScript-Completions#22]
I've updated the Javascript completion tools and it's not getting rid of the menu in the toolbar.

```
{
  "enable_can_i_use_menu_option": false
}
```

<img width="1268" alt="screen shot 2016-11-12 at 8 00 35 pm" src="https://cloud.githubusercontent.com/assets/1614348/20243007/bb18e94e-a912-11e6-8c65-03df52e0139d.png">

**Comment by pichillilorenzo** [comment]
`"enable_can_i_use_menu_option"` is for the "Can i use?" option in the context menu and not for Package Settings > JavaScript Completions Tools

**Comment by cameronroe** [comment]
How do I turn off the context menu?

**Comment by pichillilorenzo** [comment]
Try the new version and let me know!
Thanks for the support
