### ISSUE TITLE
Non-standard JSDoc configuration file

### ISSUE THREAD

**Issue by jrmull** [pichillilorenzo/JavaScript-Completions#27]
What is the logic in using a non-standard configuration file?  For example, one of the options included in the jsdoc-settings.json file:

```
{
  "destination_folder": "out",
}
```
In a 'standard' [JSDoc config file](http://usejsdoc.org/about-configuring-jsdoc.html#tags-and-tag-dictionaries) this would be:

```
{
    "opts": {
        "destination": "./out/"
    }
}
```

Intuitively, shouldn't the JavaScript Completions Tools 'Generate Documentation' command simply invoke JSDoc with the '-c' switch for a standard file name?  Like so:

`jsdoc -c jsdoc-settings.json`

In it's current state, invoking JSDoc with the '-c' switch with JavaScript-Completions requires a config file that specifies yet another config file by the "jsdoc_conf_file" property.

**Comment by pichillilorenzo** [comment]
Yes you are right, my fault! I will update it.

**Comment by pichillilorenzo** [comment]
Try the new version and let me know!
Thanks for the support
