### ISSUE TITLE
disabling of `enable_on_hover_description` doesn't work

### ISSUE THREAD

**Issue by sajadabedi** [pichillilorenzo/JavaScript-Completions#28]
I wanna disable on hover description but when I changed in package settings in `package settings > javascript completions> settings - default` to false. it doesn't happened anything. after that I copy this option and paste in `settings - user` but still doesn't work.

How can I disable on hover description?

![image](https://cloud.githubusercontent.com/assets/5726597/22454940/a580aa8e-e79e-11e6-803f-79caeed72f2c.png)

Thank you so much.

**Comment by pichillilorenzo** [comment]
From your image i can see that this "on hover" description is not coming from my plugin. Check other plugin!
