### ISSUE TITLE
"Can I use" feature not working

### ISSUE THREAD

**Issue by FeBe95** [pichillilorenzo/JavaScript-Completions#31]
Hi, the "can I use" feature doesn't work for me. Executed via the context menu or the keymap both do nothing. Changing the cursor position or selecting the word doesn't help either. The debug console prints:
```
File "C:\Users\Felix\AppData\Roaming\Sublime Text 3\Packages\JavaScript Completions\_generated_2016_09_26_at_21_37_12.py", line 926, in run
    can_i_use_data = can_i_use_file.get("data")
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by pichillilorenzo** [comment]
Try the new version and let me know!
Thanks for the support

**Comment by FeBe95** [comment]
Yes, it works now! Thanks!

**Comment by cheoAlejo** [comment]
Hi, the same error here. I have already the latest version (2.6.7)

**Comment by pichillilorenzo** [comment]
@cheoAlejo ok, so try to go into my package folder and go to the "helper" folder -> "can_i_use" folder -> delete "can_i_use_data.json" file. 
After that close sublime text and reopen it! Let me know if it works! 
Thanks!

**Comment by pichillilorenzo** [comment]
@cheoAlejo however could you post the logs from sublime text's console please??

**Comment by cheoAlejo** [comment]
Yes, it works now, thanks for the workaround. Deleting the `can_i_use_data.json` worked, only that it's name was `can_i_use_data2.json`.

**Comment by pichillilorenzo** [comment]
@cheoAlejo i use can_i_use_data2.json to test if can_i_use_data.json is the latest version! If it is a new version, can_i_use_data2.json will replace it!
