### ISSUE TITLE
Hide the "JavaScript Completions Tools" menu

### ISSUE THREAD

**Issue by Paviluf** [pichillilorenzo/JavaScript-Completions#32]
Hello,

It will be very great if we had the possibility to hide the "JavaScript Completions Tools" menu. On my laptop on Fedora 25 that make the window too wide to use the "snap" windows (2 windows side by side) feature.

Thanks !

**Comment by dogancelik** [comment]
There is actually a Menu for all Tools named "Tools"

![tools](https://cloud.githubusercontent.com/assets/486818/23583629/94f37b4c-0152-11e7-9030-282a9528bca8.png)

**Comment by pichillilorenzo** [comment]
I update the plugin! Check now
