### ISSUE TITLE
Multiple Completions shown

### ISSUE THREAD

**Issue by skube** [pichillilorenzo/JavaScript-Completions#33]
I doubt this is a real issue as it's probably something I'm not understanding or have misconfigured. 

Should there be so many?
 
![available completions](https://cloud.githubusercontent.com/assets/146396/23515904/a0a63abc-ff39-11e6-9d8c-f208aebc62a0.png)

**Comment by pichillilorenzo** [comment]
No no there is no problems.
The fact is that there are some repetitions for some words! I will update it soon
