### ISSUE TITLE
Huge lag

### ISSUE THREAD

**Issue by MOONLIGHTV** [pichillilorenzo/JavaScript-Completions#35]
I don‘t know what's happend. 
After I removed the JavaScript-Completions and installed back, there is a huge lag caused by something in JavaScript-Completions plugin between each letter I enterd, I can't write a whole word.

**Comment by pichillilorenzo** [comment]
Which version of Sublime Text are you using?
Which OS?
Can you post logs from Sublime Text's console??
Thanks!

**Comment by MOONLIGHTV** [comment]
**The version of ST3 is 3083(run on windows10).**

When I installed JavaScript-Completions and use it ,the console will still show me Exception in thread Thread-xxx, xxx is continues to increase...I removed JavaScript-Completions, then Exception in thread Thread desappeared.

![default](https://cloud.githubusercontent.com/assets/14039419/24247075/1f721c9a-1005-11e7-95bd-3fc6979e5381.png)

**Comment by MOONLIGHTV** [comment]
I intalled ST3 3126, Sublime Text's console then intalled 5 missing dependencies and restarted
I don't know what's wrong as the same but  lag disappeared...  strange..

**Comment by pichillilorenzo** [comment]
ok! I think it was because of Sublime Text version!
In their [API Reference](https://www.sublimetext.com/docs/3/api_reference.html#sublime.Window) `status_message` is a method of `sublime.Window` Class, so I think it was a bug of Sublime self.
