### ISSUE TITLE
"updating npm dependencies" every startup

### ISSUE THREAD

**Issue by MOONLIGHTV** [pichillilorenzo/JavaScript-Completions#37]
"updating npm dependencies" every startup if installed Javascript-Completions, it disappeared after removed this plugin, so, How can I close "updating npm dependencies" if I need to ues this plugin?

**Comment by pichillilorenzo** [comment]
"updating npm dependencies" checks if my plugin need an update for its npm dependencies!

It works as follows:

The first time my plugin will install its npm dependencies, after that each time you start sublime text, my plugin will check for updates (for example if i release a new plugin version, I could specify a new version of one of npm dependecies in the package.json)

If it not disappear after a while, maybe there was an error during installation.
So if you have this problem, could you remove and install it again and then post here the logs from Sublime Text's console after that please??
However what is your OS and your specific Sublime Text version?

Thanks for the support!

**Comment by MOONLIGHTV** [comment]
Hey guy~thanks a lot for answered me.
The plugin is perfect except "updating npm dependencies" .
I just want to know is there some way to close this updata check ? 
It let me feels uncomfortable...maybe I'm a squeamish...

**Comment by pichillilorenzo** [comment]
Checking for packages is important! I could hide the message in this case ok?

**Comment by yazdi** [comment]
Hi,
1. in the menu go to Performances > Browse Packages
2. go to folder JavaScript Completions > node
3. and open **installer.py**
4. comment `def updateNPMDependencies():` , it's from **line 169 to 184**
5. comment `if nodejs_already_installed :` , **line 209 and 210**
