### ISSUE TITLE
It can work but No prompt.

### ISSUE THREAD

**Issue by MOONLIGHTV** [pichillilorenzo/JavaScript-Completions#38]
It can work but No prompt show me.
The Error:

`Error: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\JavaScript Completions\_generated_2017_04_09_at_16_06_42.py", line 776, in donwload_can_i_use_json_data
    os.rename(path_to_test_can_i_use_data, path_to_can_i_use_data)
PermissionError: [WinError 32] El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso:'C:\\Users\\Administrator\\AppData\\Roaming\\Sublime Text 3\\Packages\\JavaScript Completions\\helper\\can_i_use\\can_i_use_data.json'`

**Comment by MOONLIGHTV** [comment]
If I remove this plugin and restart sublime, there is another error:
`Package Control: Unable to remove old directory JavaScript Completions - deferring until next start`
I got a headache...too many errors about this plugin.

**Comment by MOONLIGHTV** [comment]
I removed everything ,uninstalled Sublime text 3126 and reinstalled Sublime text, then I installed javascript-completions Latest version but it showed me the same Error.

It seems that there is something wrong in **_generated_2017_04_09_at_16_06_42.py**and **helper\\can_i_use\\can_i_use_data.json** (My system is windows 10)

**Comment by pichillilorenzo** [comment]
yes i know about this error, 
but "Can I use" feature must work in any case!

Isn't it working to you??

**Comment by MOONLIGHTV** [comment]
It's very strange...I restarted sublime 10 times and watched the console of sublime，8 times showed me the Error after "updating npm dependencies" finished, 2 times there is nothing appeared...

I don't know what's the "Can I use",when I write someting....the javascript-completions plugin can work but can't show me the code selection window...Now I use the sublimeCodeInter plugin to show the selection window...

**Comment by pichillilorenzo** [comment]
mmm it's very strange.. 
I will test it again on Windows 10 and I will let you know if I can reproduce this bug!

**Comment by MOONLIGHTV** [comment]
I updated the Node.js from v6.10.2 to v7.9.0,and reset the **envionment variables**, it seems like it fixed,the selection panel can be actived.

But if I set the NativeScript true in completion_active_list option,some javasctipt functions appeared many **duplicated Options**, suck as **addEventListener**
![gif](https://cloud.githubusercontent.com/assets/14039419/25031213/df303f40-20fd-11e7-9701-e4edcaa6b7e1.gif)

**Comment by pichillilorenzo** [comment]
ok.. it was strange! i don't know why it wasn't working before.

Yeah because Nativescript has many type of this function.
I generate my sublime-completions with a scraper because there are a lot of functions that i can't write by hand and alone! 

However i'm thinking on deleting Nativescript completions because it adds a lot of functions and confusion and i think no one is using it.

What do you think about that?

Thanks!

**Comment by MOONLIGHTV** [comment]
Sure, at least Nativescript is useless for me.
May be you can think about a plan to add some useful es2015 Api suck as: generator、promise、class extends、template string、arrow function、Set/Map、and so on.
It's time to step into new age now,and if it come true I'll no longer need my es6 snippets plugin...

**Comment by pichillilorenzo** [comment]
About this i'm working on a new and better plugin: [https://github.com/pichillilorenzo/JavaScriptEnhancements](https://github.com/pichillilorenzo/JavaScriptEnhancements)

Take a look to it

**Comment by MOONLIGHTV** [comment]
Ok~I‘ve watched it and star.  I'll have a try if it release a stable version.
