### ISSUE TITLE
map(function(index, elem){})

### ISSUE THREAD

**Issue by pinggod** [pichillilorenzo/JavaScript-Completions#4]
When i use this package in ST3, i typed `map` and  return this:

```js
map(function(index, elem) {
    return something;
})
```

It's always confusing me，could you fix it?

**Comment by pichillilorenzo** [comment]
I don't understand what you mean. What do you propose?

**Comment by pinggod** [comment]
Shouldn't it be:

```javascript
map(function(elem, index) {
    return something;
})
```

When i typed `map`，the arguments now is `index, elem`，and i think it will confusing users.

**Comment by pichillilorenzo** [comment]
It is strange. 
The `map` definition in this plugin is: `map(${0:callback})` and it is located here: https://github.com/pichillilorenzo/JavaScript-Completions/blob/master/JavaScript%20Completions/Array%2C%20String%20and%20RegExp/array-string-and-regexp.sublime-completions
Maybe it is one of your installed plugins that have this problem.

**Comment by pinggod** [comment]
Thanks for helping.
