### ISSUE TITLE
key maping what is super? and hover_description not really working

### ISSUE THREAD

**Issue by ohnooo** [pichillilorenzo/JavaScript-Completions#40]
First of all I just want to thank you for this awesome plugin I have been trying to find something similar to this for a very very long time.

Few suggestions: 
You might want to add installation instructions on your doc, because not everyone is familiar with Sublime's Package Control. And also let them know after installing the package its best to restart sublime. 

When you don't restart after installation a lot of things don't work for example 'find javascript description' result in 'not found' and perference>package settings> JavaScript completions> settings(default) will show a blank page.  I installed and deleted your packages so many times I almost gave up, so be sure to note everyone to start sublime.

Problems:
1. "enable_on_hover_description": true,  I have made sure its set to true... but doesn't seem to work.  Does it just takes a little time? or there is some settings I need to do...

2. in the keymap what is "keys": ["ctrl+super+d"],  I have tried command key but doesn't work.

Thank you again

**Comment by pichillilorenzo** [comment]
Ok thank you for your support!!

- However can you send me the Sublime Text logs please? Maybe there are some errors about the on hover feature!
- There isn't a keymap with "keys": ["ctrl+super+d"]
