### ISSUE TITLE
Installing node JS in windows when i have a node version installed

### ISSUE THREAD

**Issue by itsjzt** [pichillilorenzo/JavaScript-Completions#41]
when I try to install JavaScript-Completions it installs a version of node JS for itself even when I have the latest version of node JS pre-installed,
 Actually I want to know how to disable this behavior

OS: Windows 10,
Sublime Version: 3126

**Comment by pichillilorenzo** [comment]
This plugin will install node.js for itself and not globally on your computer!
So it will not override your node.js.

**Comment by jztsaurabh** [comment]
can't it use the globally installed node

**Comment by icepole-jon** [comment]
may try defined
  "node_js_custom_path": "YOUR/PATH",
  "npm_custom_path": "YOUR/PATH",
in JavaScript Completions setting
