### ISSUE TITLE
To prevent sublime autocompleter popup after semicolon(;) at the end of line

### ISSUE THREAD

**Issue by abhi0002** [pichillilorenzo/JavaScript-Completions#43]
![screenshot from 2017-10-18 11-20-07](https://user-images.githubusercontent.com/31202616/31709873-eeea9768-b410-11e7-951b-c799014a6566.png)
![screenshot from 2017-10-18 11-18-44](https://user-images.githubusercontent.com/31202616/31709875-ef1fd0cc-b410-11e7-9a7d-93d0222d502d.png)
After ;, i.e at the end of each line when I press enter , I get word 'prototype' is added() by the auto completer.I i press shift+enter then acts as normal enter without any autocomplete. added. How can I stop auto-completion after a semi-colon?
and this is the list of packages I have installed..If any of these packages causing problem plz help me out

**Comment by nickhstr** [comment]
Have you disabled SublimeCodeIntel for JavaScript?
I'm running just JavaScript Completions, and I have not experienced this issue yet.

**Comment by abhi0002** [comment]
I have not disabled JavaScript completions.Its still enabled. and fortunately i solved my issue by myself. A package called 'Auto Complete JavaScript With Method Signature ' was creating this problem. I disabled this package and my issue was solved.
