### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by cferdinandi** [pichillilorenzo/JavaScript-Completions#47]
I wanted to take a moment to say thanks for all of your work JS Completions over the years. This is one of my favorite plugins, and I love how it works so much better than what's offered for editors like VS Code.

I know you've moved on to [JS Enhancements](https://github.com/pichillilorenzo/JavaScriptEnhancements), and I wanted to let you know how sad I am about this plugins deprecation.

> It turns Sublime Text into a JavaScript IDE like!

That is, unfortunately, not something I want.

As a fellow OSS project owner, I 100% support your decision to take your project that you create for free in whatever direction you want, and wish you nothing but the best of luck.

But I did also want to ask/plead/beg you not to stop developing this one, if at all possible. And if not, I completely understand.

Thanks again!

**Comment by pichillilorenzo** [comment]
Hi @cferdinandi! 
You could use [JavaScript Enhancements](https://github.com/pichillilorenzo/JavaScriptEnhancements) plugin without using the "project features" (features will be activated only in projects and not in other files! 👍 ), so you will get all the advantages using Flow respect to the completions of that old plugin! 

You will have better autocompletions and also the latest one, with more definitions support (thanks to [flow-typed](https://github.com/flowtype/flow-typed)). Just try the new plugin 😄

**Comment by cferdinandi** [comment]
Aha... I'm unfamiliar with Flow. I'll have to look into that. Thanks again, and please do know that I greatly appreciate all of the work you've put in.

There's few things more frustrating than demanding consumers of free software!

**Comment by pichillilorenzo** [comment]
@cferdinandi Thanks! 😄 . However Flow will work also in plain javascript! You aren't forced to write javascript code in flow way (I mean using types like `let foo : Array<number> = [1, 2]`), so you could still write code normally `let foo = [1, 2]`.
