### ISSUE TITLE
Can I use key binding on windows

### ISSUE THREAD

**Issue by darbula** [pichillilorenzo/JavaScript-Completions#48]
In [docs](http://docs.sublimetext.info/en/latest/reference/key_bindings.html#warning-about-bindable-keys) there is a warning:

> If you’re developing a package, keep this in mind:
>
> * Ctrl+Alt+<alphanum> should never be used in any Windows key bindings.

And in this package `ctrl+alt+w` is used for Can I use feature [here](https://github.com/pichillilorenzo/JavaScript-Completions/blob/master/Default%20(Windows).sublime-keymap#L25).

**Comment by pichillilorenzo** [comment]
Ok thanks! So I will just change the corresponding key binding 👍, also in my new plugin!
