### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by etienned** [pichillilorenzo/JavaScript-Completions#49]
https://github.com/pichillilorenzo/JavaScript-Completions/blob/3e818d3b9b33d8da2b8b4093bfee709269855979/_generated_2017_04_09_at_16_06_42.py#L211

You call `get` on `result` but `result` can be `None` sometimes. `result` is the result of `Util.get_current_region_scope` function and this function can return `None` when no region contains selection.

**Comment by pichillilorenzo** [comment]
@etienned thanks you but, like I said in the README file, I'm focusing on the other plugin JavaScript Enhancement! It is already a better plugin then this one.

**Comment by etienned** [comment]
Great! Thanks for your work and I'll check your new plugin.
