### ISSUE TITLE
Don't work within AngularJS context

### ISSUE THREAD

**Issue by MxJ24** [pichillilorenzo/JavaScript-Completions#6]
This plugin don't work in AngualrJS context but works in pure Javascript context.
The env is Mac OS X 10.10.5 Sublime Text 3 3083

**Comment by pichillilorenzo** [comment]
This plugin works with all file with scope: "source.js" .. AngularJS is just a framework of Javascript, so it seems impossible that it doesn't work.. maybe i don't understand what you mean or maybe you have a plugin that is in contrast with mine.
However i tested it in a simple javascript file with some AngularJS functions and it works perfectly!
