### ISSUE TITLE
getElements HTML document object can be much better.

### ISSUE THREAD

**Issue by akashchgupta** [pichillilorenzo/JavaScript-Completions#7]
## **Inverted comma missing:**
**Actual:**
getElementById(Id)

**Should be:**
getElementById("Id")

for much faster coding. Thank you. You deserve many more stars.

**Comment by pichillilorenzo** [comment]
Thank you :)

Yeah it could be, but maybe someone will use a variable and not the direct string in it.
However you can simply use the single quote, so you will have `getElementById('Id')` that is a sort of compromise.

This is what i think :)

What do you think about it?

**Comment by akashchgupta** [comment]
When we are using getElementById, in most of the cases we are thinking of passing an id attribute defined in my HTML, which requires the inverted commas. 

So, I think inverted commas should be the default. Passing a variable is a bit advanced practice.

I'm a beginner to JS. I would suggest you thinking about it before putting it live. 

Thank you.
