### ISSUE TITLE
Snippets and other completions gone

### ISSUE THREAD

**Issue by MiguelDebruyne** [pichillilorenzo/JavaScript-Completions#8]
Hello there

After installing the plugin I can't use my own JS snippets anymore, they are completely gone. I also don't get any other auto completions anymore like variable names from within the file. What exactly is going on here? I'm having the same problem with the 'JavaScript Ultimate' plugin.

> Sublime Text 3 Build 3103
> OSX 10.11.4 El Capitan

**Comment by pichillilorenzo** [comment]
Sorry, but i don't know! 
This plugin contains only auto completions. No python code.
I have same Sublime Text version on OSX 10.11.3 El Capitan and it works fine.
I don't have other plugins about auto completions for javascript.

**Comment by paradite** [comment]
Same problem here. Seems like the default completion of variable names have been disabled. 

![screen shot 2016-07-19 at 11 56 51 am](https://cloud.githubusercontent.com/assets/1209810/16938190/ff54d1fc-4da7-11e6-99e1-a871ef62d2e3.png)

I am using this plugin together with [JavaScript Snippets](https://github.com/jprichardson/sublime-js-snippets)

**Comment by paradite** [comment]
Update: the default completion and snippets will appear after all the snippets from JavaScript-Completions have failed to match.

![screen shot 2016-07-19 at 12 25 01 pm](https://cloud.githubusercontent.com/assets/1209810/16938576/e5af8d10-4dab-11e6-8b53-281eed6895d6.png)
![screen shot 2016-07-19 at 12 25 15 pm](https://cloud.githubusercontent.com/assets/1209810/16938578/e7d100ec-4dab-11e6-8100-a516406ccc28.png)

**Comment by pichillilorenzo** [comment]
Ah ok ok! I didn't understand he meant that!
So this is the same for me. I have the same issue:

> the default completion and snippets will appear after all the snippets from JavaScript-Completions have failed to match.

But I think this is a problem of Sublime Text itself! Like I said, this plugin contains only auto completions. It is very simple. No python code! So, maybe, the problem depends on how completions has been implemented in Sublime Text.

Alternatively , I do not know how to solve this problem!

**Comment by paradite** [comment]
@pichillilorenzo thanks for the reply.
I searched around and found out that some other devs have avoided this problem by using `.sublime-settings` instead of `.sublime-completions`:

See this issue:
https://github.com/Pleasurazy/Sublime-Better-Completion/issues/3

And the author of the package's commit to resolve the issue:
https://github.com/Pleasurazy/Sublime-Better-Completion/commit/ccd8e2e49b8a38fedd32a843e3b2898dd5df721a

You can try doing the same in case you have some free time!

**Comment by pichillilorenzo** [comment]
I updated it! You could check if it works now!
Sorry if it took me so long!
Thanks @paradite for the link!!

**Comment by paradite** [comment]
Seems that the package control has not updated the package yet:

https://packagecontrol.io/packages/JavaScript%20Completions

**Comment by pichillilorenzo** [comment]
I know but try to uninstall and reinstall the package! It is working for me

**Comment by paradite** [comment]
@pichillilorenzo yes it is working now after removing the installing the package again. Thanks for the update!

**Comment by pichillilorenzo** [comment]
Ok! With this update you also can enable or disable one or all completions if you want!
