### ISSUE TITLE
disabled some snippets

### ISSUE THREAD

**Issue by romaopedro** [pichillilorenzo/JavaScript-Completions#9]
Hi, there are a way to disabled some snippets.

I can't use my variables because there are so many completions from package. I would like to disable some and list what I need. There are a config file or other way?

**Comment by pichillilorenzo** [comment]
I updated it! Now you can enable or disable what you want here: Preferences -> Package Settings -> JavaScript Completions -> Settings - User
Tell me what you think about it and sorry if it took me so long!
@romaopedro

**Comment by romaopedro** [comment]
I decided to not use anymore this package. I realized that the snippets that I was using were few and so I created my own. 

But I tested you settings file and it works good and it will help other users for sure.
